
build-back:
  image: maven:3.8.1-jdk-11-slim
  stage: build
  script:
    - cd api
    - mvn clean package -Dmaven.test.skip=true

build-front:
  image: node:10-alpine
  stage: build
  script:
    - cd front
    - npm install
    - npm run ng build

test-back:
  image: maven:3.8.1-jdk-11-slim
  services:
    - mysql:latest
  variables:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: tlc
    MYSQL_USER: tlc
    MYSQL_PASSWORD: tlc
  stage: test
  script:
    - cd api
    - mvn clean test

test-front:
  image: node:10-alpine
  stage: test
  script:
    - cd front
    - npm install
    - npm run ng test
