stages:
  - validate
  - build
  - test
  - integration

.maven:
  image: maven:3.8.1-jdk-11-slim
  cache:
    key: maven-$CI_COMMIT_REF_SLUG
    paths:
      - api/.m2/repository/
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
    MAVEN_CLI_OPTS: "-Dmaven.repo.local=.m2/repository -Dstyle.color=always"

compile-back:
  extends: .maven
  stage: validate
  script:
    - cd api
    - mvn clean compile
  artifacts:
    when: on_failure
    paths:
      - api/target/checkstyle-result.xml

build-back:
  extends: .maven
  stage: build
  needs:
    - job: compile-back
  script:
    - cd api
    - mvn clean package -Dmaven.test.skip=true -Dquarkus.package.type=uber-jar
  artifacts:
    paths:
      - api/target/tlcdemoApp-1.0.0-SNAPSHOT.jar
    expire_in: 1 week

build-front:
  image: node:10-alpine
  stage: build
  script:
    - cd front
    - npm install
    - npm run ng build

test-back:
  extends: .maven
  stage: test
  needs:
    - job: build-back
  services:
    - mysql
  variables:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: tlc
    MYSQL_USER: tlc
    MYSQL_PASSWORD: tlc
    SERVER_NAME: mysql:3306
  script:
    - cd api
    - mvn test
  artifacts:
    paths:
      - api/target/tlcdemoApp-1.0.0-SNAPSHOT.jar
    reports:
      junit:
        - api/target/surefire-reports/TEST-*.xml

test-front:
  image: node:10-alpine
  stage: test
  needs:
    - job: build-front
  before_script:
    - apk add chromium
    - export CHROME_BIN=/usr/bin/chromium-browser
  script:
    - cd front
    - npm install
    - ./node_modules/.bin/ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
  artifacts:
    reports:
      junit:
        - front/artifacts/tests/junit-test-results.xml

test-integration:
  image: node:10-alpine
  stage: integration
  services:
    - mysql
  needs:
    - job: test-back
    - job: test-front
  variables:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: tlc
    MYSQL_USER: tlc
    MYSQL_PASSWORD: tlc
    SERVER_NAME: mysql:3306
  script:
    - java -jar api/target/tlcdemoApp-1.0.0-SNAPSHOT.jar &
    - cd front
    - npm install
    - ./node_modules/.bin/ng e2e