.maven:
  image: maven:3.8.1-jdk-11-slim
  cache:
    key: maven-$CI_COMMIT_REF_SLUG
    paths:
      - api/.m2/repository/
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
    MAVEN_CLI_OPTS: "-Dmaven.repo.local=.m2/repository -Dstyle.color=always"

build-back:
  extends: .maven
  stage: build
  script:
    - cd api
    - mvn clean package -Dmaven.test.skip=true
  artifacts:
    paths:
      - api/target/tlcdemoApp-1.0.0-SNAPSHOT.jar
    expire_in: 1 week

#build-front:
#  image: node:10-alpine
#  stage: build
#  script:
#    - cd front
#    - npm install
#    - npm run ng build

test-back:
  extends: .maven
  stage: test
  services:
    - mysql
  variables:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: tlc
    MYSQL_USER: tlc
    MYSQL_PASSWORD: tlc
    SERVER_NAME: mysql:3306
  script:
    - cd api
    - mvn clean test
  artifacts:
    paths:
      - api/target/surefire-reports
    expire_in: 1 week

#test-front:
#  image: node:10-alpine
#  stage: test
#  script:
#    - cd front
#    - npm install
#    - npm run ng test
