version: "3.8"
services:
  back:
    image: maven:3.8.1-jdk-11-slim
    build: ./api/
    depends_on:
      - db
      - etherpad
      - mail
    environment:
      SERVER_NAME: db
      BACK_PORT: 8127
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
  etherpad:
    image: etherpad/etherpad:stable
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
  front:
    build: ./front

